# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-11 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediumArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.TextField(default='')),
                ('creator', models.CharField(default='', max_length=500)),
                ('title', models.TextField(default='')),
                ('date', models.DateField()),
                ('read_time', models.IntegerField(default=0)),
                ('details', models.TextField(default='')),
                ('blog', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'MediumArticle',
                'verbose_name_plural': 'MediumArticles',
            },
        ),
        migrations.CreateModel(
            name='MediumSearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(default='')),
                ('tag_data', models.TextField(default='[]')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('articles', models.ManyToManyField(blank=True, to='MediumScrapperApp.MediumArticle')),
            ],
            options={
                'verbose_name': 'MediumSearchData',
                'verbose_name_plural': 'MediumSearchDatas',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='mediumarticle',
            name='tags',
            field=models.ManyToManyField(blank=True, to='MediumScrapperApp.Tag'),
        ),
    ]
