# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-12 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediumScrapperApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediumarticle',
            name='details',
        ),
        migrations.AddField(
            model_name='mediumsearchdata',
            name='search_data',
            field=models.TextField(default='[]'),
        ),
        migrations.RemoveField(
            model_name='mediumarticle',
            name='tags',
        ),
        migrations.AddField(
            model_name='mediumarticle',
            name='tags',
            field=models.TextField(default='[]'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
