# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MediumScrapperApp', '0002_auto_20200512_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediumarticle',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
