# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediumScrapperApp', '0003_auto_20200512_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediumarticle',
            name='comments',
            field=models.TextField(default='[]'),
        ),
    ]
