# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-12 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediumScrapperApp', '0004_mediumarticle_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediumsearchdata',
            name='no_of_results',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediumsearchdata',
            name='raw_json_data',
            field=models.TextField(default='{}'),
        ),
    ]
